package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/cdreier/kubeql/graph/model"
)

// Yaml is the resolver for the yaml field.
func (r *configMapResolver) Yaml(ctx context.Context, obj *model.ConfigMap) (string, error) {
	if obj.Missing {
		return "", nil
	}
	return r.Svc.ConfigMapYAML(ctx, obj.Context, obj.Namespace, obj.Name)
}

// ConfigMaps is the resolver for the configMaps field.
func (r *queryResolver) ConfigMaps(ctx context.Context, context string, namespace string) ([]*model.ConfigMap, error) {
	list, err := r.Svc.ListConfigMaps(ctx, context, namespace)
	if err != nil {
		return nil, err
	}
	return toConfigMaps(context, list), nil
}

// ConfigMap is the resolver for the configMap field.
func (r *queryResolver) ConfigMap(ctx context.Context, context string, namespace string, name string) (*model.ConfigMap, error) {
	cm, err := r.Svc.GetConfigMap(ctx, context, namespace, name)
	if err != nil {
		return nil, err
	}
	if cm == nil {
		return nil, nil
	}
	return toConfigMap(context, *cm), nil
}

// ConfigMap returns ConfigMapResolver implementation.
func (r *Resolver) ConfigMap() ConfigMapResolver { return &configMapResolver{r} }

type configMapResolver struct{ *Resolver }
