package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"log"

	"github.com/cdreier/kubeql/graph/model"
)

// Namespaces is the resolver for the namespaces field.
// Cluster errors (unreachable API, stale kubeconfig, etc.) are logged and
// returned as an empty list so sibling contexts still resolve.
func (r *kubeContextResolver) Namespaces(ctx context.Context, obj *model.KubeContext, filter *model.NamespaceFilter) ([]*model.Namespace, error) {
	list, err := r.Svc.ListNamespaces(ctx, obj.Name, mapNamespaceFilter(filter))
	if err != nil {
		log.Printf("kubeql: context %q namespaces: %v (returning empty list)", obj.Name, err)
		return []*model.Namespace{}, nil
	}
	return toNamespaces(obj.Name, list), nil
}

// Namespace is the resolver for the namespace field.
func (r *kubeContextResolver) Namespace(ctx context.Context, obj *model.KubeContext, name string) (*model.Namespace, error) {
	ns, err := r.Svc.GetNamespace(ctx, obj.Name, name)
	if err != nil {
		log.Printf("kubeql: context %q namespace %q: %v (returning null)", obj.Name, name, err)
		return nil, nil
	}
	if ns == nil {
		return nil, nil
	}
	return toNamespace(obj.Name, *ns), nil
}

// Deployments is the resolver for the deployments field.
func (r *kubeContextResolver) Deployments(ctx context.Context, obj *model.KubeContext, namespace *string, filter *model.DeploymentFilter) ([]*model.Deployment, error) {
	deps, err := r.Svc.ListDeployments(ctx, obj.Name, nsOrEmpty(namespace), mapDeploymentFilter(filter))
	if err != nil {
		log.Printf("kubeql: context %q deployments: %v (returning empty list)", obj.Name, err)
		return []*model.Deployment{}, nil
	}
	return toDeployments(obj.Name, deps), nil
}

// Deployment is the resolver for the deployment field.
func (r *kubeContextResolver) Deployment(ctx context.Context, obj *model.KubeContext, namespace string, name string) (*model.Deployment, error) {
	d, err := r.Svc.GetDeployment(ctx, obj.Name, namespace, name)
	if err != nil {
		log.Printf("kubeql: context %q deployment %s/%s: %v (returning null)", obj.Name, namespace, name, err)
		return nil, nil
	}
	if d == nil {
		return nil, nil
	}
	return toDeployment(obj.Name, *d), nil
}

// Pods is the resolver for the pods field.
func (r *kubeContextResolver) Pods(ctx context.Context, obj *model.KubeContext, namespace *string, filter *model.PodFilter) ([]*model.Pod, error) {
	pods, err := r.Svc.ListPods(ctx, obj.Name, nsOrEmpty(namespace), mapPodFilter(filter))
	if err != nil {
		log.Printf("kubeql: context %q pods: %v (returning empty list)", obj.Name, err)
		return []*model.Pod{}, nil
	}
	return toPods(obj.Name, pods), nil
}

// Pod is the resolver for the pod field.
func (r *kubeContextResolver) Pod(ctx context.Context, obj *model.KubeContext, namespace string, name string) (*model.Pod, error) {
	p, err := r.Svc.GetPod(ctx, obj.Name, namespace, name)
	if err != nil {
		log.Printf("kubeql: context %q pod %s/%s: %v (returning null)", obj.Name, namespace, name, err)
		return nil, nil
	}
	if p == nil {
		return nil, nil
	}
	return toPod(obj.Name, *p), nil
}

// Contexts is the resolver for the contexts field.
func (r *queryResolver) Contexts(ctx context.Context) ([]*model.KubeContext, error) {
	return toKubeContexts(r.Svc.ListContexts()), nil
}

// KubeContext returns KubeContextResolver implementation.
func (r *Resolver) KubeContext() KubeContextResolver { return &kubeContextResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type kubeContextResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
