package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"log"
	"time"

	"github.com/cdreier/kubeql/graph/model"
)

// Yaml is the resolver for the yaml field.
func (r *cronJobResolver) Yaml(ctx context.Context, obj *model.CronJob) (string, error) {
	return r.Svc.CronJobYAML(ctx, obj.Context, obj.Namespace, obj.Name)
}

// Jobs is the resolver for the jobs field.
func (r *cronJobResolver) Jobs(ctx context.Context, obj *model.CronJob) ([]*model.Job, error) {
	cj, err := r.Svc.GetCronJob(ctx, obj.Context, obj.Namespace, obj.Name)
	if err != nil {
		return nil, err
	}
	if cj == nil {
		return []*model.Job{}, nil
	}
	jobs, err := r.Svc.JobsForCronJob(ctx, obj.Context, *cj)
	if err != nil {
		return nil, err
	}
	return toJobs(obj.Context, jobs), nil
}

// Pods is the resolver for the pods field.
func (r *cronJobResolver) Pods(ctx context.Context, obj *model.CronJob, filter *model.PodFilter) ([]*model.Pod, error) {
	cj, err := r.Svc.GetCronJob(ctx, obj.Context, obj.Namespace, obj.Name)
	if err != nil {
		return nil, err
	}
	if cj == nil {
		return []*model.Pod{}, nil
	}
	pods, err := r.Svc.PodsForCronJob(ctx, obj.Context, *cj, mapPodFilter(filter))
	if err != nil {
		return nil, err
	}
	return toPods(obj.Context, pods), nil
}

// ConfigMaps is the resolver for the configMaps field.
func (r *cronJobResolver) ConfigMaps(ctx context.Context, obj *model.CronJob) ([]*model.ConfigMap, error) {
	cj, err := r.Svc.GetCronJob(ctx, obj.Context, obj.Namespace, obj.Name)
	if err != nil {
		return nil, err
	}
	if cj == nil {
		return []*model.ConfigMap{}, nil
	}
	list, err := r.Svc.ConfigMapsForCronJob(ctx, obj.Context, *cj)
	if err != nil {
		return nil, err
	}
	return toConfigMaps(obj.Context, list), nil
}

// Secrets is the resolver for the secrets field.
func (r *cronJobResolver) Secrets(ctx context.Context, obj *model.CronJob) ([]*model.Secret, error) {
	cj, err := r.Svc.GetCronJob(ctx, obj.Context, obj.Namespace, obj.Name)
	if err != nil {
		return nil, err
	}
	if cj == nil {
		return []*model.Secret{}, nil
	}
	list, err := r.Svc.SecretsForCronJob(ctx, obj.Context, *cj)
	if err != nil {
		return nil, err
	}
	return toSecrets(obj.Context, list), nil
}

// Yaml is the resolver for the yaml field.
func (r *jobResolver) Yaml(ctx context.Context, obj *model.Job) (string, error) {
	return r.Svc.JobYAML(ctx, obj.Context, obj.Namespace, obj.Name)
}

// Pods is the resolver for the pods field.
func (r *jobResolver) Pods(ctx context.Context, obj *model.Job, filter *model.PodFilter) ([]*model.Pod, error) {
	j, err := r.Svc.GetJob(ctx, obj.Context, obj.Namespace, obj.Name)
	if err != nil {
		return nil, err
	}
	if j == nil {
		return []*model.Pod{}, nil
	}
	pods, err := r.Svc.PodsForJob(ctx, obj.Context, *j, mapPodFilter(filter))
	if err != nil {
		return nil, err
	}
	return toPods(obj.Context, pods), nil
}

// CronJobs is the resolver for the cronJobs field.
func (r *kubeContextResolver) CronJobs(ctx context.Context, obj *model.KubeContext, namespace *string, filter *model.CronJobFilter) ([]*model.CronJob, error) {
	list, err := r.Svc.ListCronJobs(ctx, obj.Name, nsOrEmpty(namespace), mapCronJobFilter(filter))
	if err != nil {
		log.Printf("kubeql: context %q cronJobs: %v (returning empty list)", obj.Name, err)
		return []*model.CronJob{}, nil
	}
	return toCronJobs(obj.Name, list), nil
}

// CronJob is the resolver for the cronJob field.
func (r *kubeContextResolver) CronJob(ctx context.Context, obj *model.KubeContext, namespace string, name string) (*model.CronJob, error) {
	cj, err := r.Svc.GetCronJob(ctx, obj.Name, namespace, name)
	if err != nil {
		log.Printf("kubeql: context %q cronJob %s/%s: %v (returning null)", obj.Name, namespace, name, err)
		return nil, nil
	}
	if cj == nil {
		return nil, nil
	}
	return toCronJob(obj.Name, *cj), nil
}

// CronJobs is the resolver for the cronJobs field.
func (r *namespaceResolver) CronJobs(ctx context.Context, obj *model.Namespace, filter *model.CronJobFilter) ([]*model.CronJob, error) {
	list, err := r.Svc.ListCronJobs(ctx, obj.Context, obj.Name, mapCronJobFilter(filter))
	if err != nil {
		return nil, err
	}
	return toCronJobs(obj.Context, list), nil
}

// CronJobs is the resolver for the cronJobs field.
func (r *queryResolver) CronJobs(ctx context.Context, context string, namespace *string, filter *model.CronJobFilter) ([]*model.CronJob, error) {
	list, err := r.Svc.ListCronJobs(ctx, context, nsOrEmpty(namespace), mapCronJobFilter(filter))
	if err != nil {
		return nil, err
	}
	return toCronJobs(context, list), nil
}

// CronJob is the resolver for the cronJob field.
func (r *queryResolver) CronJob(ctx context.Context, context string, namespace string, name string) (*model.CronJob, error) {
	cj, err := r.Svc.GetCronJob(ctx, context, namespace, name)
	if err != nil {
		return nil, err
	}
	if cj == nil {
		return nil, nil
	}
	return toCronJob(context, *cj), nil
}

// CronJobStatus is the resolver for the cronJobStatus field.
func (r *subscriptionResolver) CronJobStatus(ctx context.Context, context string, namespace string, name string) (<-chan *model.CronJob, error) {
	ch := make(chan *model.CronJob, 1)
	go func() {
		defer close(ch)
		var last string
		ticker := time.NewTicker(2 * time.Second)
		defer ticker.Stop()

		emit := func() bool {
			cj, err := r.Svc.GetCronJob(ctx, context, namespace, name)
			if err != nil || cj == nil {
				return true
			}
			jobs, _ := r.Svc.JobsForCronJob(ctx, context, *cj)
			pods, _ := r.Svc.PodsForCronJob(ctx, context, *cj, nil)
			key := cronJobLiveKey(*cj, jobs, pods)
			if key == last {
				return true
			}
			last = key
			select {
			case <-ctx.Done():
				return false
			case ch <- toCronJob(context, *cj):
				return true
			}
		}

		if !emit() {
			return
		}
		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				if !emit() {
					return
				}
			}
		}
	}()
	return ch, nil
}

// CronJob returns CronJobResolver implementation.
func (r *Resolver) CronJob() CronJobResolver { return &cronJobResolver{r} }

// Job returns JobResolver implementation.
func (r *Resolver) Job() JobResolver { return &jobResolver{r} }

type cronJobResolver struct{ *Resolver }
type jobResolver struct{ *Resolver }
