package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"log"

	"github.com/cdreier/kubeql/graph/model"
)

// Yaml is the resolver for the yaml field.
func (r *customResourceResolver) Yaml(ctx context.Context, obj *model.CustomResource) (string, error) {
	return r.Svc.CustomResourceYAML(ctx, obj.Context, obj.Group, obj.Version, obj.Resource, nsOrEmpty(obj.Namespace), obj.Name)
}

// APIResources is the resolver for the apiResources field.
func (r *kubeContextResolver) APIResources(ctx context.Context, obj *model.KubeContext) ([]*model.APIResource, error) {
	list, err := r.Svc.ListAPIResources(ctx, obj.Name, nil)
	if err != nil {
		log.Printf("kubeql: context %q apiResources: %v (returning empty list)", obj.Name, err)
		return []*model.APIResource{}, nil
	}
	return toAPIResources(list), nil
}

// CustomResources is the resolver for the customResources field.
func (r *kubeContextResolver) CustomResources(ctx context.Context, obj *model.KubeContext, namespace *string, filter *model.CustomResourceFilter) ([]*model.CustomResource, error) {
	list, err := r.Svc.ListCustomResources(ctx, obj.Name, nsOrEmpty(namespace), mapCustomResourceFilter(filter))
	if err != nil {
		log.Printf("kubeql: context %q customResources: %v (returning empty list)", obj.Name, err)
		return []*model.CustomResource{}, nil
	}
	return toCustomResources(obj.Name, list), nil
}

// CustomResources is the resolver for the customResources field.
func (r *namespaceResolver) CustomResources(ctx context.Context, obj *model.Namespace, filter *model.CustomResourceFilter) ([]*model.CustomResource, error) {
	list, err := r.Svc.ListCustomResources(ctx, obj.Context, obj.Name, mapCustomResourceFilter(filter))
	if err != nil {
		return nil, err
	}
	return toCustomResources(obj.Context, list), nil
}

// APIResources is the resolver for the apiResources field.
func (r *namespaceResolver) APIResources(ctx context.Context, obj *model.Namespace) ([]*model.APIResource, error) {
	ns := true
	list, err := r.Svc.ListAPIResources(ctx, obj.Context, &ns)
	if err != nil {
		return nil, err
	}
	return toAPIResources(list), nil
}

// APIResources is the resolver for the apiResources field.
func (r *queryResolver) APIResources(ctx context.Context, context string) ([]*model.APIResource, error) {
	list, err := r.Svc.ListAPIResources(ctx, context, nil)
	if err != nil {
		return nil, err
	}
	return toAPIResources(list), nil
}

// CustomResources is the resolver for the customResources field.
func (r *queryResolver) CustomResources(ctx context.Context, context string, namespace *string, filter *model.CustomResourceFilter) ([]*model.CustomResource, error) {
	list, err := r.Svc.ListCustomResources(ctx, context, nsOrEmpty(namespace), mapCustomResourceFilter(filter))
	if err != nil {
		return nil, err
	}
	return toCustomResources(context, list), nil
}

// CustomResource is the resolver for the customResource field.
func (r *queryResolver) CustomResource(ctx context.Context, context string, group string, version string, resource string, namespace *string, name string) (*model.CustomResource, error) {
	cr, err := r.Svc.GetCustomResource(ctx, context, group, version, resource, nsOrEmpty(namespace), name)
	if err != nil {
		return nil, err
	}
	if cr == nil {
		return nil, nil
	}
	return toCustomResource(context, *cr), nil
}

// CustomResource returns CustomResourceResolver implementation.
func (r *Resolver) CustomResource() CustomResourceResolver { return &customResourceResolver{r} }

type customResourceResolver struct{ *Resolver }
