package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"time"

	"github.com/cdreier/kubeql/graph/model"
)

// Yaml is the resolver for the yaml field.
func (r *deploymentResolver) Yaml(ctx context.Context, obj *model.Deployment) (string, error) {
	return r.Svc.DeploymentYAML(ctx, obj.Context, obj.Namespace, obj.Name)
}

// Pods is the resolver for the pods field.
func (r *deploymentResolver) Pods(ctx context.Context, obj *model.Deployment, filter *model.PodFilter) ([]*model.Pod, error) {
	d, err := r.Svc.GetDeployment(ctx, obj.Context, obj.Namespace, obj.Name)
	if err != nil {
		return nil, err
	}
	if d == nil {
		return []*model.Pod{}, nil
	}
	pods, err := r.Svc.PodsForDeployment(ctx, obj.Context, *d, mapPodFilter(filter))
	if err != nil {
		return nil, err
	}
	return toPods(obj.Context, pods), nil
}

// Restarts is the resolver for the restarts field.
func (r *deploymentResolver) Restarts(ctx context.Context, obj *model.Deployment) (int, error) {
	d, err := r.Svc.GetDeployment(ctx, obj.Context, obj.Namespace, obj.Name)
	if err != nil {
		return 0, err
	}
	if d == nil {
		return 0, nil
	}
	n, err := r.Svc.DeploymentRestarts(ctx, obj.Context, *d)
	if err != nil {
		return 0, err
	}
	return int(n), nil
}

// ConfigMaps is the resolver for the configMaps field.
func (r *deploymentResolver) ConfigMaps(ctx context.Context, obj *model.Deployment) ([]*model.ConfigMap, error) {
	d, err := r.Svc.GetDeployment(ctx, obj.Context, obj.Namespace, obj.Name)
	if err != nil {
		return nil, err
	}
	if d == nil {
		return []*model.ConfigMap{}, nil
	}
	list, err := r.Svc.ConfigMapsForDeployment(ctx, obj.Context, *d)
	if err != nil {
		return nil, err
	}
	return toConfigMaps(obj.Context, list), nil
}

// Secrets is the resolver for the secrets field.
func (r *deploymentResolver) Secrets(ctx context.Context, obj *model.Deployment) ([]*model.Secret, error) {
	d, err := r.Svc.GetDeployment(ctx, obj.Context, obj.Namespace, obj.Name)
	if err != nil {
		return nil, err
	}
	if d == nil {
		return []*model.Secret{}, nil
	}
	list, err := r.Svc.SecretsForDeployment(ctx, obj.Context, *d)
	if err != nil {
		return nil, err
	}
	return toSecrets(obj.Context, list), nil
}

// Deployments is the resolver for the deployments field.
func (r *queryResolver) Deployments(ctx context.Context, context string, namespace *string, filter *model.DeploymentFilter) ([]*model.Deployment, error) {
	deps, err := r.Svc.ListDeployments(ctx, context, nsOrEmpty(namespace), mapDeploymentFilter(filter))
	if err != nil {
		return nil, err
	}
	return toDeployments(context, deps), nil
}

// Deployment is the resolver for the deployment field.
func (r *queryResolver) Deployment(ctx context.Context, context string, namespace string, name string) (*model.Deployment, error) {
	d, err := r.Svc.GetDeployment(ctx, context, namespace, name)
	if err != nil {
		return nil, err
	}
	if d == nil {
		return nil, nil
	}
	return toDeployment(context, *d), nil
}

// DeploymentStatus is the resolver for the deploymentStatus field.
// MVP: poll GetDeployment until the subscription context is cancelled.
func (r *subscriptionResolver) DeploymentStatus(ctx context.Context, context string, namespace string, name string) (<-chan *model.Deployment, error) {
	ch := make(chan *model.Deployment, 1)
	go func() {
		defer close(ch)
		var last string
		ticker := time.NewTicker(2 * time.Second)
		defer ticker.Stop()

		emit := func() bool {
			d, err := r.Svc.GetDeployment(ctx, context, namespace, name)
			if err != nil || d == nil {
				return true
			}
			pods, _ := r.Svc.PodsForDeployment(ctx, context, *d, nil)
			key := deploymentLiveKey(*d, pods)
			if key == last {
				return true
			}
			last = key
			select {
			case <-ctx.Done():
				return false
			case ch <- toDeployment(context, *d):
				return true
			}
		}

		if !emit() {
			return
		}
		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				if !emit() {
					return
				}
			}
		}
	}()
	return ch, nil
}

// Deployment returns DeploymentResolver implementation.
func (r *Resolver) Deployment() DeploymentResolver { return &deploymentResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type deploymentResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
