package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/cdreier/kubeql/graph/model"
)

// Deployments is the resolver for the deployments field.
func (r *namespaceResolver) Deployments(ctx context.Context, obj *model.Namespace, filter *model.DeploymentFilter) ([]*model.Deployment, error) {
	deps, err := r.Svc.ListDeployments(ctx, obj.Context, obj.Name, mapDeploymentFilter(filter))
	if err != nil {
		return nil, err
	}
	return toDeployments(obj.Context, deps), nil
}

// Pods is the resolver for the pods field.
func (r *namespaceResolver) Pods(ctx context.Context, obj *model.Namespace, filter *model.PodFilter) ([]*model.Pod, error) {
	pods, err := r.Svc.ListPods(ctx, obj.Context, obj.Name, mapPodFilter(filter))
	if err != nil {
		return nil, err
	}
	return toPods(obj.Context, pods), nil
}

// Namespaces is the resolver for the namespaces field.
func (r *queryResolver) Namespaces(ctx context.Context, context string, filter *model.NamespaceFilter) ([]*model.Namespace, error) {
	list, err := r.Svc.ListNamespaces(ctx, context, mapNamespaceFilter(filter))
	if err != nil {
		return nil, err
	}
	return toNamespaces(context, list), nil
}

// Namespace is the resolver for the namespace field.
func (r *queryResolver) Namespace(ctx context.Context, context string, name string) (*model.Namespace, error) {
	ns, err := r.Svc.GetNamespace(ctx, context, name)
	if err != nil {
		return nil, err
	}
	if ns == nil {
		return nil, nil
	}
	return toNamespace(context, *ns), nil
}

// Namespace returns NamespaceResolver implementation.
func (r *Resolver) Namespace() NamespaceResolver { return &namespaceResolver{r} }

type namespaceResolver struct{ *Resolver }
