package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"time"

	"github.com/cdreier/kubeql/graph/model"
	"github.com/cdreier/kubeql/internal/kube"
)

// Yaml is the resolver for the yaml field.
func (r *podResolver) Yaml(ctx context.Context, obj *model.Pod) (string, error) {
	return r.Svc.PodYAML(ctx, obj.Context, obj.Namespace, obj.Name)
}

// Pods is the resolver for the pods field.
func (r *queryResolver) Pods(ctx context.Context, context string, namespace *string, filter *model.PodFilter) ([]*model.Pod, error) {
	pods, err := r.Svc.ListPods(ctx, context, nsOrEmpty(namespace), mapPodFilter(filter))
	if err != nil {
		return nil, err
	}
	return toPods(context, pods), nil
}

// Pod is the resolver for the pod field.
func (r *queryResolver) Pod(ctx context.Context, context string, namespace string, name string) (*model.Pod, error) {
	p, err := r.Svc.GetPod(ctx, context, namespace, name)
	if err != nil {
		return nil, err
	}
	if p == nil {
		return nil, nil
	}
	return toPod(context, *p), nil
}

// PodLogs is the resolver for the podLogs field.
func (r *subscriptionResolver) PodLogs(ctx context.Context, context string, namespace string, name string, container *string, tailLines *int) (<-chan *model.LogLine, error) {
	opts := kube.LogOptions{
		Namespace: namespace,
		Pod:       name,
		Follow:    true,
	}
	if container != nil {
		opts.Container = *container
	}
	if tailLines != nil {
		n := int64(*tailLines)
		opts.TailLines = &n
	}

	stream, err := r.Svc.StreamPodLogs(ctx, context, opts)
	if err != nil {
		return nil, fmt.Errorf("stream logs: %w", err)
	}

	ch := make(chan *model.LogLine, 32)
	go func() {
		defer close(ch)
		defer stream.Close()

		scanner := bufio.NewScanner(stream)
		// Allow long log lines.
		scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
		for scanner.Scan() {
			line := scanner.Text()
			msg := &model.LogLine{Line: line, Container: container}
			if ts, rest, ok := splitLogTimestamp(line); ok {
				msg.Timestamp = &ts
				msg.Line = rest
			}
			select {
			case <-ctx.Done():
				return
			case ch <- msg:
			}
		}
		// Drain scanner error only if context still active.
		if err := scanner.Err(); err != nil && ctx.Err() == nil && err != io.EOF {
			// Surface as a final synthetic line rather than failing the subscription mid-flight.
			select {
			case <-ctx.Done():
			case ch <- &model.LogLine{Line: "log stream error: " + err.Error(), Container: container}:
			}
		}
	}()
	return ch, nil
}

// PodStatus is the resolver for the podStatus field.
// MVP: poll GetPod until the subscription context is cancelled.
func (r *subscriptionResolver) PodStatus(ctx context.Context, context string, namespace string, name string) (<-chan *model.Pod, error) {
	ch := make(chan *model.Pod, 1)
	go func() {
		defer close(ch)
		var last string
		ticker := time.NewTicker(2 * time.Second)
		defer ticker.Stop()

		emit := func() bool {
			p, err := r.Svc.GetPod(ctx, context, namespace, name)
			if err != nil || p == nil {
				return true
			}
			key := fmt.Sprintf("%s|%v|%d|%s|%s|%s",
				p.Phase, p.Ready, p.Restarts, p.NodeName, derefStr(p.CPUUsage), derefStr(p.MemoryUsage))
			if key == last {
				return true
			}
			last = key
			select {
			case <-ctx.Done():
				return false
			case ch <- toPod(context, *p):
				return true
			}
		}

		if !emit() {
			return
		}
		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				if !emit() {
					return
				}
			}
		}
	}()
	return ch, nil
}

// Pod returns PodResolver implementation.
func (r *Resolver) Pod() PodResolver { return &podResolver{r} }

type podResolver struct{ *Resolver }
