package graph

import "github.com/cdreier/kubeql/internal/kube"

// This file will not be regenerated by gqlgen.
// It holds dependency injection for resolvers.

// Resolver is the root resolver with shared dependencies.
type Resolver struct {
	Svc *kube.Service
}

// NewResolver constructs the root resolver.
func NewResolver(svc *kube.Service) *Resolver {
	return &Resolver{Svc: svc}
}
