package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/cdreier/kubeql/graph/model"
)

// Secrets is the resolver for the secrets field.
func (r *queryResolver) Secrets(ctx context.Context, context string, namespace string) ([]*model.Secret, error) {
	list, err := r.Svc.ListSecrets(ctx, context, namespace)
	if err != nil {
		return nil, err
	}
	return toSecrets(context, list), nil
}

// Secret is the resolver for the secret field.
func (r *queryResolver) Secret(ctx context.Context, context string, namespace string, name string) (*model.Secret, error) {
	sec, err := r.Svc.GetSecret(ctx, context, namespace, name)
	if err != nil {
		return nil, err
	}
	if sec == nil {
		return nil, nil
	}
	return toSecret(context, *sec), nil
}

// Yaml is the resolver for the yaml field.
func (r *secretResolver) Yaml(ctx context.Context, obj *model.Secret) (string, error) {
	if obj.Missing {
		return "", nil
	}
	return r.Svc.SecretYAML(ctx, obj.Context, obj.Namespace, obj.Name)
}

// Secret returns SecretResolver implementation.
func (r *Resolver) Secret() SecretResolver { return &secretResolver{r} }

type secretResolver struct{ *Resolver }
