// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// A discovered API resource that is not a built-in Kubernetes kind (typically a CRD).
type APIResource struct {
	Group   string `json:"group"`
	Version string `json:"version"`
	Kind    string `json:"kind"`
	// Plural resource name, e.g. kustomizations.
	Resource   string `json:"resource"`
	Namespaced bool   `json:"namespaced"`
}

type ConfigMap struct {
	// Kubeconfig context this resource was loaded from.
	Context   string `json:"context"`
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
	// How a parent deployment references this object (env, envFrom, volume, …).
	Refs []string `json:"refs"`
	// True when the object was referenced but not found in the cluster.
	Missing bool        `json:"missing"`
	Keys    []string    `json:"keys"`
	Data    []*KeyValue `json:"data"`
	// Full object as YAML.
	Yaml string `json:"yaml"`
}

type Container struct {
	Name         string `json:"name"`
	Image        string `json:"image"`
	Ready        bool   `json:"ready"`
	RestartCount int    `json:"restartCount"`
	// e.g. Running, Waiting, Terminated.
	State string `json:"state"`
}

type CronJob struct {
	// Kubeconfig context this resource was loaded from.
	Context   string `json:"context"`
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
	// Cron schedule, e.g. "0 * * * *".
	Schedule string `json:"schedule"`
	// IANA time zone from spec.timeZone, if set.
	TimeZone *string `json:"timeZone,omitempty"`
	Suspend  bool    `json:"suspend"`
	// Allow, Forbid, or Replace.
	ConcurrencyPolicy  string     `json:"concurrencyPolicy"`
	LastScheduleTime   *time.Time `json:"lastScheduleTime,omitempty"`
	LastSuccessfulTime *time.Time `json:"lastSuccessfulTime,omitempty"`
	// Number of currently active jobs.
	Active int `json:"active"`
	// Human-readable summary: Suspended, Idle, or Active N.
	Status string   `json:"status"`
	Labels []*Label `json:"labels"`
	// Full object as YAML.
	Yaml string `json:"yaml"`
	// Jobs owned by this CronJob, newest first.
	Jobs []*Job `json:"jobs"`
	// Pods belonging to owned jobs.
	Pods []*Pod `json:"pods"`
	// ConfigMaps referenced by the job template.
	ConfigMaps []*ConfigMap `json:"configMaps"`
	// Secrets referenced by the job template.
	Secrets []*Secret `json:"secrets"`
}

// Filter cron jobs by name/labels and optional suspend state.
type CronJobFilter struct {
	// Case-insensitive substring match on cron job name.
	NameContains *string `json:"nameContains,omitempty"`
	// Kubernetes label selector (e.g. "app=backup").
	LabelSelector *string `json:"labelSelector,omitempty"`
	// When set, only cron jobs with this spec.suspend value.
	Suspended *bool `json:"suspended,omitempty"`
}

// A generic custom resource instance (Flux Kustomization, cert-manager Certificate, …).
type CustomResource struct {
	// Kubeconfig context this resource was loaded from.
	Context    string `json:"context"`
	APIVersion string `json:"apiVersion"`
	Kind       string `json:"kind"`
	Group      string `json:"group"`
	Version    string `json:"version"`
	Resource   string `json:"resource"`
	Name       string `json:"name"`
	// Null when the resource is cluster-scoped.
	Namespace *string  `json:"namespace,omitempty"`
	Labels    []*Label `json:"labels"`
	// status.conditions type=Ready (or Healthy/Available). Null when unknown.
	Ready     *bool      `json:"ready,omitempty"`
	Reason    *string    `json:"reason,omitempty"`
	Message   *string    `json:"message,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Full object as YAML.
	Yaml string `json:"yaml"`
}

type CustomResourceFilter struct {
	// Case-insensitive substring match on resource name.
	NameContains *string `json:"nameContains,omitempty"`
	// Case-insensitive substring on kind, resource, or API group (e.g. flux).
	KindContains *string `json:"kindContains,omitempty"`
	Group        *string `json:"group,omitempty"`
	Version      *string `json:"version,omitempty"`
	Kind         *string `json:"kind,omitempty"`
	Resource     *string `json:"resource,omitempty"`
}

type Deployment struct {
	// Kubeconfig context this resource was loaded from.
	Context           string `json:"context"`
	Name              string `json:"name"`
	Namespace         string `json:"namespace"`
	Replicas          int    `json:"replicas"`
	ReadyReplicas     int    `json:"readyReplicas"`
	AvailableReplicas int    `json:"availableReplicas"`
	// Human-readable summary, e.g. "3/3" or condition reason.
	Status string   `json:"status"`
	Labels []*Label `json:"labels"`
	// Full object as YAML.
	Yaml string `json:"yaml"`
	// Pods owned by this deployment (via label selector).
	Pods []*Pod `json:"pods"`
	// Sum of container restart counts across owned pods.
	Restarts int `json:"restarts"`
	// ConfigMaps referenced by the pod template (env, envFrom, volumes).
	ConfigMaps []*ConfigMap `json:"configMaps"`
	// Secrets referenced by the pod template (env, envFrom, volumes, imagePull).
	Secrets []*Secret `json:"secrets"`
}

// Filter deployments by name/labels and optionally by owned pods.
type DeploymentFilter struct {
	// Case-insensitive substring match on deployment name.
	NameContains *string `json:"nameContains,omitempty"`
	// Kubernetes label selector (e.g. "app=api,tier=frontend").
	LabelSelector *string `json:"labelSelector,omitempty"`
	// Keep deployments that have at least one pod matching this filter.
	HasPod *PodFilter `json:"hasPod,omitempty"`
}

type Job struct {
	// Kubeconfig context this resource was loaded from.
	Context     string `json:"context"`
	Name        string `json:"name"`
	Namespace   string `json:"namespace"`
	Completions int    `json:"completions"`
	Succeeded   int    `json:"succeeded"`
	Failed      int    `json:"failed"`
	Active      int    `json:"active"`
	// Complete, Failed, Running, or Pending.
	Status         string     `json:"status"`
	StartTime      *time.Time `json:"startTime,omitempty"`
	CompletionTime *time.Time `json:"completionTime,omitempty"`
	Labels         []*Label   `json:"labels"`
	// Full object as YAML.
	Yaml string `json:"yaml"`
	// Pods owned by this job.
	Pods []*Pod `json:"pods"`
}

// A string map entry (ConfigMap/Secret data, etc.).
type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// A context entry from the loaded kubeconfig.
// Cluster resources are nested here so one clientset is used per context.
type KubeContext struct {
	Name    string `json:"name"`
	Cluster string `json:"cluster"`
	User    string `json:"user"`
	// Default namespace from the kubeconfig context entry, if set.
	DefaultNamespace *string `json:"defaultNamespace,omitempty"`
	// True if this is the CLI/--context or kubeconfig current-context default.
	Current bool `json:"current"`
	// List namespaces in this context.
	// Unreachable/stale clusters log the error and return [] so other contexts still resolve.
	Namespaces []*Namespace `json:"namespaces"`
	// Get a single namespace in this context. Null if missing or cluster unreachable.
	Namespace *Namespace `json:"namespace,omitempty"`
	// List deployments. Namespace is optional (all namespaces when omitted).
	// Unreachable clusters return [] (same best-effort behavior as namespaces).
	Deployments []*Deployment `json:"deployments"`
	// Get a single deployment in this context. Null if missing or cluster unreachable.
	Deployment *Deployment `json:"deployment,omitempty"`
	// List pods. Namespace is optional (all namespaces when omitted).
	// Unreachable clusters return [] (same best-effort behavior as namespaces).
	Pods []*Pod `json:"pods"`
	// Get a single pod in this context. Null if missing or cluster unreachable.
	Pod *Pod `json:"pod,omitempty"`
	// List cron jobs. Namespace is optional (all namespaces when omitted).
	CronJobs []*CronJob `json:"cronJobs"`
	// Get a single cron job in this context. Null if missing or cluster unreachable.
	CronJob *CronJob `json:"cronJob,omitempty"`
	// Discovered extension API resources (CRDs).
	APIResources []*APIResource `json:"apiResources"`
	// Custom resources. Namespace is optional (all namespaces when omitted).
	CustomResources []*CustomResource `json:"customResources"`
}

type Label struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type LogLine struct {
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Line      string     `json:"line"`
	Container *string    `json:"container,omitempty"`
}

type Namespace struct {
	// Kubeconfig context this resource was loaded from.
	Context     string        `json:"context"`
	Name        string        `json:"name"`
	Deployments []*Deployment `json:"deployments"`
	Pods        []*Pod        `json:"pods"`
	CronJobs    []*CronJob    `json:"cronJobs"`
	// Namespaced custom resources in this namespace (CRDs / extension APIs).
	CustomResources []*CustomResource `json:"customResources"`
	// Discovered namespaced extension API resources (CRDs).
	APIResources []*APIResource `json:"apiResources"`
}

// Filter namespaces by name and/or by whether they contain matching resources.
// Example: namespaces that have a deployment whose name contains "api".
type NamespaceFilter struct {
	// Case-insensitive substring match on namespace name.
	NameContains *string `json:"nameContains,omitempty"`
	// Keep namespaces that have at least one deployment matching this filter.
	HasDeployment *DeploymentFilter `json:"hasDeployment,omitempty"`
	// Keep namespaces that have at least one pod matching this filter.
	HasPod *PodFilter `json:"hasPod,omitempty"`
}

type Pod struct {
	// Kubeconfig context this resource was loaded from.
	Context       string     `json:"context"`
	Name          string     `json:"name"`
	Namespace     string     `json:"namespace"`
	Phase         string     `json:"phase"`
	Ready         bool       `json:"ready"`
	Restarts      int        `json:"restarts"`
	LastRestartAt *time.Time `json:"lastRestartAt,omitempty"`
	// Pod creation time (metadata.creationTimestamp).
	CreatedAt  *time.Time   `json:"createdAt,omitempty"`
	NodeName   *string      `json:"nodeName,omitempty"`
	Labels     []*Label     `json:"labels"`
	Containers []*Container `json:"containers"`
	// Full object as YAML.
	Yaml string `json:"yaml"`
	// Optional; requires metrics-server. Null when unavailable.
	CPUUsage *string `json:"cpuUsage,omitempty"`
	// Sum of container CPU limits from the pod spec. Null when unset.
	CPULimit *string `json:"cpuLimit,omitempty"`
	// Optional; requires metrics-server. Null when unavailable.
	MemoryUsage *string `json:"memoryUsage,omitempty"`
	// Sum of container memory limits from the pod spec. Null when unset.
	MemoryLimit *string `json:"memoryLimit,omitempty"`
}

// Filter pods by name, labels, phase, and readiness.
type PodFilter struct {
	// Case-insensitive substring match on pod name.
	NameContains *string `json:"nameContains,omitempty"`
	// Kubernetes label selector (e.g. "app=api").
	LabelSelector *string `json:"labelSelector,omitempty"`
	// Exact pod phase (Pending, Running, Succeeded, Failed, Unknown).
	Phase *string `json:"phase,omitempty"`
	// When set, only pods with this overall ready state.
	Ready *bool `json:"ready,omitempty"`
}

type Query struct {
}

type Secret struct {
	// Kubeconfig context this resource was loaded from.
	Context   string `json:"context"`
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
	// Kubernetes secret type, e.g. Opaque, kubernetes.io/tls.
	Type string `json:"type"`
	// How a parent deployment references this object (env, envFrom, volume, imagePull).
	Refs []string `json:"refs"`
	// True when the object was referenced but not found in the cluster.
	Missing bool     `json:"missing"`
	Keys    []string `json:"keys"`
	// Decoded values when UTF-8; otherwise a binary placeholder.
	Data []*KeyValue `json:"data"`
	// Full object as YAML.
	Yaml string `json:"yaml"`
}

type Subscription struct {
}
